sudo: required
language: node_js
node_js:
      - "7"
services:
    - docker
before_install:
    docker build -t evgenik22/react-test -f ./client/Dockerfile.dev ./client
script:
    docker run evgenik22/react-test  npm test -- --coverage
after_success:
    - docker build -t evgenik22/multi-client ./client
    - docker build -t evgenik22/multi-server ./server
    - docker build -t evgenik22/multi-nginx  ./ngnix
    - docker build -t evgenik22/multi-worker ./worker
    - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
    - docker push evgenik22/multi-server:latest 
    - docker push evgenik22/multi-nginx:latest  
    - docker push evgenik22/multi-client:latest 
    - docker push evgenik22/multi-worker:latest 
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-729597639361
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"
        
 
