sudo: required
services:
    - docker
before_install:
    docker build -t evgenik22/react-test -f ./client/Dockerfile.dev ./client
script:
    docker run evgenik22/react-test  npm test -- --coverage
    - docker build -t evgenik22/multi-client ./client
    - docker build -t evgenik22/multi-server ./server
    - docker build -t evgenik22/multi-ngnix  ./ngnix
    - docker build -t evgenik22/multi-worker ./worker
after_success:
    - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD 
    - docker push evgenik22/multi-client:latest 
    - docker push evgenik22/multi-server:latest 
    - docker push evgenik22/multi-ngnix:latest  
    - docker push evgenik22/multi-worker:latest 
